[package]
name = "dev_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.*", features = ["full"] } # parse rust code into dt
quote = "1.*"  # gen rust code from dt
proc-macro2 = "1.*"  # proc macro helper
